### ISSUE TITLE
T.Joy theme css problems [solved]

### ISSUE THREAD

**Issue by apos** [RedburnM/WordpressAstrometry#4]
Hi,,

I could solve some css problems in our T.Jouy astronomy theme. Therefore I had to alter the **astrometry.css**:
I added the following things:

Problems with text, that floats over the box:
- .astrometry-data > * { white-space: wrap; }

Problems with coordinates that wrap (should not) in the column:
- .astrometry-data > .col2 {  white-space nowrap; }
- .astrometry-data > .col4 {  white-space nowrap; }

Font of rows are not allowed (label and corresponding text): 
- .astrometry-data label { margin-top: 0.777777777em;}

Added some fixes to the **global T.Joy theme css**:

/* astrometry fix*/
/* image won't fit into the overlay picture */
img.solved  {
  max-width: none !important;
  width: 100% !important;
}

.equipment {
    white-space: wrap !important;
}

**Comment by MattChique** [comment]
I hopefully fixed your css issues.

- Image size should now work properly, in normal mode and in fullsize mode.
- Coords don't wrap anymore
- The margin thing is some inherited from your theme, so i set padding and margin  to 0!important. You have to remove your margin-top: 0.777777777em; from your modified css.

**Comment by apos** [comment]
Hi Matt, perfect :-) Deling with themes and css is always a difficult task. Thanks for your fast response and implementation of the solutions (wrapping coords, padding and margins).

There remains one problem [1.] and a new occured [2.]:

1. I have to keep the fix for the real picture / annotation size. I think this is a special theme problem with T.Joy and can be fixed without hassle globally with the following code :-) The other fixed are not needed any more - thanks.


    /* astrometry fix */
    img.solved  {
      max-width: none !important;
      width: 100% !important;
    }


2. But fhe fullscreen mode is not working any more like in your demo: https://www.explorespace.de/2020/m45/ 
This worked before if I remember right. Now I see, that my theme uses img.solved**.jetpack-lazy-image.jetpack-lazy-image--handled** as selector which could be the problem?!

I could get working it again, deleting some new code in the new version. I got - almost - everything back: the annotation however is slighly disalaligned using this code. This was the case with the old code (from Juli 2020 too):

(astrometry.css.new -> Dec 29 20202: https://github.com/MattChique/WordpressAstrometry/commit/a23f0e6b9a92af66ad64e8c15e31be93a4aa0ede#diff-690d03bb19dd15d34a545fe631217b9141f4b1e5a9071c8438360914317fd524) 
```
"astrometry.css" 265L, 7217C written
[root@nethserver css]# diff astrometry.css astrometry.css.
28c28
<   /* display: flex;
---
>   display: flex;
30c30
<   justify-content: center;*/
---
>   justify-content: center;
34,35c34,35
<   /*position: relative;
<   cursor:zoom-out;*/
---
>   position: relative;
>   cursor:zoom-out;
39c39
<   width: 100%!important;
---
>   width: auto!important;
47,48c47,48
<       bottom: 0px;
<       width: auto;
---
>   bottom: 0px;
>   width: 100%;
```

Thanks for your work. I will add other improvements over time to get interesting features out of the vast astrometry metasdata:-)

THX Axel

**Comment by MattChique** [comment]
Hi Axel,

the image ratio is now tied at the browsers width and height. This should not be. https://avvp.de/cygnus-wall-ngc7000/

Maybe you can revert your css changes, so i can take a look at the issue?

**Comment by apos** [comment]
Hi Matt, 

you are right. I reverse it.

The effect can easily be seen in fullscreen mode. This is with my "changes":

![2020-12-31 18_26_47-Window](https://user-images.githubusercontent.com/456034/103420331-eee38d80-4b96-11eb-8add-eec2d660bfe9.png)

![2020-12-31 18_28_39-Window](https://user-images.githubusercontent.com/456034/103420340-f60a9b80-4b96-11eb-81a1-864d41194881.png)

But when reverting to your version, the image is very small:

![2020-12-31 18_39_02-Window](https://user-images.githubusercontent.com/456034/103420459-8fd24880-4b97-11eb-8c60-b8442bdbcab8.png)

For now: HAPPY NEW YEAR :-)
Axel

**Comment by MattChique** [comment]
Finally found out, this is an issue with jetpack/photon/hosting by wordpress.com.

If you look at the source, the imagepath is https://i2.wp.com/avvp.de/wp-content/uploads/2019/03/NGC7000_CygnusWall.jpg?w=640&ssl=1

There is a w parameter, which sets the image width. Unfortunatelly, it seems that jetpack/photon/whatever sets this parameters to all images displayed on your page. The images' width is only set to 640px. This is why the zoomed image is so small. I don't know if you can disable/change this behaviour. 

I will research for a solution to turn this behaviour off for the displayed image.

**Comment by MattChique** [comment]
Can you please do one thing for me?

Just add 

`echo "<!-- astrometry " .  $content . "-->";` to the file [block/editor_block.php Line 43](https://github.com/MattChique/WordpressAstrometry/blob/master/block/editor_block.php#L43)

refresh https://avvp.de/cygnus-wall-ngc7000/ and send me the plain source code?

Thanks!

**Comment by MattChique** [comment]
@apos Maybe you try it again, please reinstall the plugin

Probably found a solution by removing the width parameter from the image url: https://github.com/MattChique/WordpressAstrometry/commit/577fd4d5034f839aa610ff2289cc12f6f5976eb9#diff-8e5ab94056ecb84acd5f18fb5439727aa4e524e281a1046719654d69bedb649cR49

**Comment by apos** [comment]
Hi Matt,

unfortunately not working. I think this is correlated to: https://github.com/Automattic/jetpack/issues/9833 

I tried the following, which also works :

```
$url = 'https://i2.wp.com/avvp.de/wp-content/uploads/2019/03/NGC7000_CygnusWall.jpg?w=640&amp;ssl=1';
$varname = "w";
echo preg_replace('/([?&])'.$varname.'=[^&]+(&|$)/','$1',$url);
```
```
//Photon/Jetpack queries images with width(w) param, we should remove it
$param_name = "w";
$content = preg_replace('/([?&])'.$param_name.'=[^&]+(&|$)/','$1',$content);
```

Problem:
This is not aplied to the webpage. If I try it in e.g. https://www.w3schools.com/php this works perfectly. 

```
<!DOCTYPE html>
<html>
<body>

<?php

$content = '<img src="https://i2.wp.com/avvp.de/wp-content/uploads/2019/03/NGC7000_CygnusWall.jpg?w=640&amp;ssl=1" class="solved jetpack-lazy-image jetpack-lazy-image--handled" data-solved="https://avvp.de/wp-content/plugins/WordpressAstrometry-master/annotation/annotations.php?mediaid=1334&amp;postid=1987&amp;showHdCatalogue=true" data-recalc-di
ms="1" data-lazy-loaded="1">';

$varname = "w";
echo preg_replace('/([?&])'.$varname.'=[^&]+(&|$)/','$1',$content);

?>

</body>
</html>
```

I am digging deeper ...

**Comment by apos** [comment]
**SOLUTION  FOUND :-) - not ideal, but works:**

1. I could remove your patch (but I keep it just in case)
2. The problem in fact is **Jetpacks speed up setting of image loading**. I had to **disable** "reduce time to load images" in JetPack.

![2021-01-01 17_43_20-Window](https://user-images.githubusercontent.com/456034/103442801-a4771500-4c59-11eb-8d2f-c08c3cdbab34.png)

Thank you so much for your time. But I think it was worth it, because a lot of people use Jetpack.

Cheers Matt, a happy new year and hopefully soon clear skies :-)
Axel

**Comment by MattChique** [comment]
Hm, not satisfying for me... what does it show in the wordpress code editor (press Ctrl+Shift+Alt+M when **editing** the wp article). 

![image](https://user-images.githubusercontent.com/26269158/103442913-78a85f00-4c5a-11eb-8def-63569ad940ba.png)

Does w param already exist in the code? Because i just registered at wp.com and startet a wp page and inserted an image from the mediathek (unfortunately I cannot use custom plugins). The image was inserted with an "w" parameter

**Comment by apos** [comment]
> Hm, not satisfying for me

:-)  developer :-) 

Editor content of the article (HTML plain text view): 

- **without** the patch:
- fast image loading in Jetpack **disabled**

```
<!-- wp:astrometry/photodata {"mediaID":1334,"showAstrometryMetaData":true,"showAstrometrySkyplot":true,"showHdCatalogue":true} -->
<div class="wp-block-astrometry-photodata"><div class="astrometry-image" data-mediaid="1334"><figure class="wp-image-1334"><img src="https://avvp.de/wp-content/uploads/2019/03/NGC7000_CygnusWall.jpg" class="{solvingState}" data-solved="{solvingData}"/></figure></div><div class="astrometry-image-data"><div class="skyplot"><div>{SKYPLOT}</div></div><div class="astrometry-data"><label>Aufnahmedatum</label><p class="date">Herbst 2018</p><label>Frames</label><p class="col2 frames"><span class="framesCount">520</span><span class="framesX info">x</span><span class="framesSeconds">180</span><span class="framesSecondsSymbol">''</span></p><label class="col3">Aufnahmedauer</label><p class="col4">26h</p><label>Ausrüstung</label><p class="equipment">Explore Scientific ED 102 APO FCD1<br/>ZWO ASI 1600MM PRO</p><p>{ASTROMETRYDATA}</p></div></div></div>
<!-- /wp:astrometry/photodata -->
```

- same with Jetpack fast image loading **enabled**:

```
<!-- wp:astrometry/photodata {"mediaID":1334,"showAstrometryMetaData":true,"showAstrometrySkyplot":true,"showHdCatalogue":true} -->
<div class="wp-block-astrometry-photodata"><div class="astrometry-image" data-mediaid="1334"><figure class="wp-image-1334"><img src="https://avvp.de/wp-content/uploads/2019/03/NGC7000_CygnusWall.jpg" 
[...]

```

**Comment by MattChique** [comment]
developer! :-D

Jetpack reduce loading time is enabled?

I just tried it at my wp.com test site, and the image image is inserted with the width param:

```<!-- wp:image {"id":35,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large">
<img src="https://mg406796791.files.wordpress.com/2021/01/ic1396-v3-hubble-2020-07-21.jpg?w=750" alt="" class="wp-image-35"/>
</figure>
<!-- /wp:image -->
```

Hm, do you host the wordpress by yourself with the jetpack plugin 

AH, i can reproduce it:
![image](https://user-images.githubusercontent.com/26269158/103443297-fae65280-4c5d-11eb-80eb-d22257fa4245.png)

**Comment by apos** [comment]
This is my server, yes (KVM). Not a paid Jetpack version, just basic. Really tricky ...

**Comment by MattChique** [comment]
I think, I found a solution using this https://jetpack.com/2013/05/03/skip-a-image-with-photon/.

**Comment by apos** [comment]
Fix works 🥇 

See: https://avvp.de/cygnus-wall-ngc7000/

**Comment by MattChique** [comment]
🎉
