### ISSUE TITLE
Equipmentbox astrometry-data - text goes outside the box [solved]

### ISSUE THREAD

**Issue by apos** [RedburnM/WordpressAstrometry#6]
After solving the css problems with Jetpack / Photen the equipmentbox looks a little bit strange on certain browser sizes: it is too small.  This will vanish, when using a big screen or the browser will be very small (responsive design). 

![2021-01-01 19_21_16-Window](https://user-images.githubusercontent.com/456034/103444304-8dd7ba80-4c67-11eb-97a2-615359984c13.png)

![2021-01-01 19_35_29-Window](https://user-images.githubusercontent.com/456034/103444448-8e248580-4c68-11eb-9a35-081977f94b0e.png)

Cheers
Axel

**Comment by apos** [comment]
Suggestion: 
- generally switch to 2 column design
- make the skyplot bigger
- size of the font within the astrometry-data can be reduced by custom css

![2021-01-01 19_46_02-Window](https://user-images.githubusercontent.com/456034/103444623-4a328000-4c6a-11eb-9335-3488b4c2b4ac.png)

**Comment by MattChique** [comment]
I will look at it (dealing with themes is so tiresome)

**Comment by apos** [comment]
Hi Matt, you don't have to: I am doing this, because this is my task using T.Joy. Thanks for your time. 
I am posting my solution here.

**Comment by apos** [comment]
I am now totally satisfied with the solution I found. I also added some changes to the css.

Problem of thread solved (I think):
- No relative values min-height/width: changed from 200px static definition to "%":
```
nano astrometry.css
.skyplot div {
  min-height: 100%;
  min-width: 100%;
}
```
Changes I did, which are not really related to the bug:
- bigger skyplot
- 2 columns layout with smaller font
-  problem found in astrometry.editor.css
```
/* bigger skyplot image */
.skyplot img {
  width: 100%!important;
}

/* relation between skyplot and data - optional */
.astrometry-image-data {
  grid-template-columns: 1.5fr 2fr;
}

/* Two column layout with less grid gab and smaller font- optional */
.astrometry-data {
  grid-template-columns: 1.5fr 2fr 0fr 0fr;
  grid-gap: 0.5rem;
  font-size: 1.4rem;
}

.astrometry-data > .col3 {
  grid-column: 1;
}
.astrometry-data > .col4 {
  grid-column: 2;
  white-space: nowrap;
}

```

Other things:
- Black background in the editor for astrometry data. Add at the end:
```
nano astrometry.editor.css
.astrometry-image-data {
    background: rgb(220,220,220)!important;
}
```
![2021-01-01 21_52_39-Window](https://user-images.githubusercontent.com/456034/103446068-b49fec00-4c7b-11eb-9cbd-4263f035b71b.png)


Thanks Matt for your plugin - I am sure our people will love it 👍

**Comment by MattChique** [comment]
Remember adding your CSS to the theme customizer, since it is a theme dependant change and to not overwrite it, if you update the plugin.

**Comment by apos** [comment]
Thanks Matt - perfect match.

P.S. just for completness and our **theme specific** changes (T.Joy). 

Unfortunately it was not possible - at least for my theme T.Joy to add custom CSS for the bock editor. For now, I therefore had to make to following changes to get the same results according to the theme layout in the Gutenberg-Editor.

Like Matt said: this should be in a custom theme css and NOT alter the plugin css file.

```
nano astrometry.editor.css

.astrometry-image-data .equipment {
     background: rgb(255,255,255);
}

.astrometry-image-data {
    background: rgb(220,220,220)!important;
}

/* bigger skyplot image */
.skyplot img {
  width: 50%!important;
}

.skyplot div {
  min-height: 25%!important;
  min-width: 25%!important;
}

/* bigger skyplot image */
.skyplot img {
  width: 25%!important;
}

/* relation between skyplot and data - optional */
.astrometry-image-data {
  grid-template-columns: 0.25fr 1.5fr!important;
}

/* Two column layout with less grid gab and smaller font- optional */
.astrometry-data {
  grid-template-columns: 0.25fr 1.5fr 0fr 0fr!important;
  grid-gap: 0.5rem;
  font-size: 1.4rem;
}

.astrometry-data > .col3 {
  grid-column: 1!important;
}
.astrometry-data > .col4 {
  grid-column: 2!important;
  white-space: nowrap!important;
}
```

![2021-01-04 17_44_11-Window](https://user-images.githubusercontent.com/456034/103558482-08494a00-4eb5-11eb-9d81-ecc2dec26b32.png)
